### PR TITLE
Add NB for review

### PR DESCRIPTION
**Pull request by AlexAndorra**
@twiecki @canyon289 this is ready for review

### CODE REVIEW

**Comment by AlexAndorra** [comment]
<p>Noted</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Noted. Just kept: accessing a group, stacking chain and draw, converting to numpy array, computing mean and quantiles</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Thanks, will reorganize content accordingly</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Took all your comments into account @canyon289

**Review by canyon289 — APPROVED** [review]
Looks great, left some minor comments.

**Comment by twiecki** [comment]
I left comments but apparently not on the PR but the file itself: https://app.reviewnb.com/AlexAndorra/notebooks-experiments/blob/script-lesson-4/alex_4.ipynb%2F/discussion

**Comment by AlexAndorra** [comment]
Thanks for the reviews @twiecki and @canyon289 ! Just added your changes, and am now gonna record the first video 🥳

**Comment by AlexAndorra** [comment]
@twiecki and @canyon289 this is ready for (final?) review! Mainly check the section about the A/B test model, as this is the big novelty.
I also added seaborn to the last section, as I needed it in the NB (and we'll probably use it from time to time during the course, so at least I'll have introduced it here).
I'll now re-record the first sections and send them to Fadi for tech approval

**Comment by AlexAndorra** [comment]
<p>Done, but it's killing me...</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Good point. I wanna show how to do that with numpy, but we can do it later</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Kept mu and sigma, and was consistent with in the code below</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>I thought we were going with plausibility as our y axis labels for most plots so Alex did it right?</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
That works. The one I was looking at didn't have a label.

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<blockquote>Why is there just one for the posterior, that should be a distribution no?</blockquote><p> </p><p>It is a distribution: <code>plausible_values_a.posterior_predictive["how_likely"]</code> , but the observations are discrete, so you get a histogram</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
I integrated all your comments @twiecki . You can merge if it looks good now.
I'm going to do a recording session this afternoon 🥳

**Comment by AlexAndorra** [comment]
Merging as we all agreed on the content

**Pull request merged**
