### PR TITLE
Hierarchical reg

### PR DESCRIPTION
**Pull request by twiecki**

### CODE REVIEW

**Comment by AlexAndorra** [comment]
<p>Mmmh, I think Thomas really mean "different", that makes sens here</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Agreed</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Agreed</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Definitely, getting that group mean is always awesome</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Typo: So you can see how the<strong>y</strong> constrain each other</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Typo: "But they all ad channels also share similarity in <em>how</em> they change over time."</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Very enjoyable read @twiecki , especially the first half 🤩 
I left a bunch of comments. Hopefully that helps making this even better!

**Comment by canyon289** [comment]
<p>Dont load the image using python however, we should get images to work properly in local markdown to avoid the one code cell line that just loads an image</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>Switching to Mutable for the homework where students should change, but yes.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>I don't see a difference in your code.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>I think they're both singular.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>The suggestion is to hide the code block, not change it</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>No need for a change as the fix is uglier in the video</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
@twiecki HEADS UP I updated this notebook so pull before you make more changes to avoid version conflict. 

Here's what I did
1. Changed the inter section title to `##
  * Why: Makes it consistent with other lessons
  * Why: In the notebook the headers make the notebooks much easier to navigate with the Table of Contents
2. Add title slides to all slides
  * Why: Because in the video it makes it clear what the takeaway for the slide is
  * Why: In the notebook the headers make the notebooks much easier to navigate with the Table of Contents
3. Renamed Section 2 final slide from conclusions to "Section Recap"
   * Why: consistency makes it easy to understand where sections start and end

**Comment by AlexAndorra** [comment]
<p>The first typo is still there</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>No this is intentional as it's abridged writing for the slide.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>instead went with Lego approach.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>Good point, this is from the unpooled estimates, which I now mention, thanks to you &lt;3.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>Who are you to tell me what to do and what not to.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>Ugh, such an embarrassing mistake, I'm sorry Alex.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>That's racist.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>Spoken like the true genius that you are.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>You're not my mom.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/6/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
Thanks everyone! will start recording.

**Pull request merged**
