### PR TITLE
Hierarchical reg

### PR DESCRIPTION
**Pull request by twiecki**

### CODE REVIEW

**Comment by canyon289** [comment]
These changes are awesome! Things makes so much better!

**Comment by twiecki** [comment]
<p>#wholesome</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by tomicapretto** [comment]
<p>I like this addition!! On top of what is already included, there's the maximum entropy argument (given mean and sd). It could be used if someone has questions about this part.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Yep, here would be a good place to do that, and I think we should</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Exactly, that was the reason behind our decision ;)</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>Thanks!</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
I downloaded the notebook and am more confused. If all the above sildes are part of the lesson intro now thats way too much. Compare it to either your original recording or Alex's intro.

If I now understand correctly those slides should be moved to Section 20, but before you do anything lets align to ensure theres no double work

https://learn.intuitivebayes.com/view/courses/intuitive-bayes-introduction/1067376-bayesian-linear-regression/3821632-lesson-introduction

**Comment by twiecki** [comment]
Yeah, conceptually it makes more sense to add it to 20.

**Comment by twiecki** [comment]
<p>it is.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>There isn't one here, couldn't find a funny one.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>Yep, it's in the note below.</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/10/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
