### PR TITLE
Distributions Rewrite

### PR DESCRIPTION
**Pull request by canyon289**
Done enough for review though needs a bit more polish

### CODE REVIEW

**Comment by twiecki** [comment]
I like it. In general it feels a bit stand-alone where it's not making many references to the previous lessons. Also in the sense that it's not using PyMC as much, so I feel like maybe you could come back to the model more.

**Comment by canyon289** [comment]
>  I like it. In general it feels a bit stand-alone where it's not making many references to the previous lessons. Also in the sense that it's not using PyMC as much, so I feel like maybe you could come back to the model more.

I fully agree with this, I'll make some better changes now. Really need @AlexAndorra to complete the tools rewrite so I know what to refer to. I plan on heavily copying from his material so there's a more direct link.

I'll apply all fixes from review now, can we do another review after tools is complete?

**Comment by canyon289** [comment]
<p>Yes</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>While I mechanically understand the second part, I don't totally get what you mean. Will ask tomorrow</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Updated the two plots to correlate better, let me know what you think, happy to revise again</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>I agree in general but In A/B test the observed data is categorical but the thing were estimating is continuous.</p><p> </p><p>Should I start with the continuous example first like heights, then show the A/B test second?</p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Oh I have an idea! @alexandorra, do you think you can fit in a continuous prior and likelihood model in the tools lesson? I can use that as a jumping off point in this lesson. Maybe you could use a simpler version of fish weights?</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Yea reviewnb is not doing us many favors here. On a related note it might be good for you to download the notebook and watch it in slide format. The reason is most of this text is notes that aren't on the slides but in reviewnb you can't tell the difference.</p><p> </p><p>Not needed for this preliminary review, but as we move to final review itd be the only way to review this as itll be seen by students</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Good idea</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Changed to Relative belief all possible values of conversion rate</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Great idea, Ill have Fadi stitch in another video of the pymc docs as I narrate over it</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>ah this slide is hidden in the notebook, I'll just delete it here</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Great call out </p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>This plot is hidden in the slides and wont be in the video, I left it in for reference with some annotation</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Hows this one? Its a bit more fun </p><p> </p><p>https://www.freepik.com/premium-vector/crowd-people-sale-discounts-stampede-danger-lot-people-excitement-panic_21565315.htm#query=stampede&amp;position=2&amp;from_view=search</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Its not quite funny but youre right let me think on it for a meme or something that would fit the bill. Agree this one is a bit too corporate</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>I cans ee that, the specific question I have then is should I try and incorporate this idea that MCMC and sampling are one and the same of course in a more cohesive way, or just leave it out entirely?</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Working on the new A/B test lesson: I'm not introducing Normal and HalfNormal priors now, so make sure to do it here @canyon289 , because we need them for the Lin Reg lesson

**Comment by canyon289** [comment]
Will do! Those are in the Bayes Distribution lesson as priors

**Comment by canyon289** [comment]
<p>Tracking here https://github.com/IntuitiveBayes/intuitive-bayesian-course/issues/190</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Sounds like this graph isnt quite landing yet, point taken there. Your comment + me thinking through a response just made me realize something we can do here to make this way better. I'll get back to you on this.</p><p> </p><p>Thank you for the feedback</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>This will be moved to bayes lesson where MCMC actually will make sense </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Alright looking at this now again, parameter I believe will make more sense because im continuing the a/b narrative arc that Alex and you established, and then introducing a new example after</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>This plot is removed</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Change this to purchases</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>Weren't you going to change the titles?</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/7/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
