### PR TITLE
Add original Lin Reg NB

### PR DESCRIPTION
**Pull request by AlexAndorra**

### CODE REVIEW

**Comment by AlexAndorra** [comment]
Ready for review @canyon289 and @twiecki 🥳

**Comment by twiecki** [comment]
I like it. I would, however, more clearly highlight / remind that instead of just a single solution, here we get multiple, and what we can do with that. I think a plot like the one with the regression line you have, just with multiple lines (like here: https://twiecki.io/blog/2013/08/12/bayesian-glms-1/). Also, maybe there is some statistical question we could ask of this data, some hypothesis, that we can then answer from the posterior in a probabilistic way?

**Comment by canyon289** [comment]
<p>I agree with this, especially because you say Flat priors and Normal likelihood it really sounds Bayesian. If you do want to keep it instead of pointing out the similarities Id point out the dissimilarities between the OLS approach and bayes</p><p> </p><p>For instance you could bring up "black box" or "play mobil" model approach where you have little control. Sure its convenient but do you really know what the estimators are? What if you wanted to change them could you?</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Agreed, also explain what log_weight/log_weight x axis label is</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>;)</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Sorry, thought it was the same country 😜</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>You mean inside a <code>pm.Data</code> container? That'd work but I wanted to isolate that step to talk about it. Inside the model it's gonna be flooded with all the other info</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Addressed</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>I added that because a few students have asked for such comparisons (I'm not the best to do that though, as I've very rarely used freq stats 😅). Let me try and rephrase. If I still can't make the point, let's drop it</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Sounds good! </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>The Tools lesson</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>I used it in the Tools lesson already</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Can you give me the elevator pitch on how to interpret rank plot? I'm always confused...</p><p>Also: then shouldn't we set that as the default in ArviZ?</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Kidman ;)</p><p>https://www.youtube.com/watch?v=ykG5dOHqUtE</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>This x-axis label is actually the default from ArviZ and I don't understand why we do that 😅</p><p>Do you know why there is this double label @Ravin?</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>This will be on another slide</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Are the v4 docs up yet?</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>I think it's good to introduce it in this lesson. I talk about it during this session already, and it plants a seed in their brain, which makes Thomas' job easier in the Hierarchical lesson</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>That should actually say "predictions", thanks Ravin</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>we have plot_rank as its own method so its there</p><p> </p><p>The basic idea is that all the histograms should be roughly uniform. The way it works is all samples from all chains are ranked, if one chain samples a different mode the ranks of its samples will be markedly higher or lower than other chains</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Perhaps add Kidman in there to make the joke more obvious?</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Unless youre goingn to verbalize it, then its fine!</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Im 99% sure it the labels for both series plotted, though I forgot why its in there twice. Id just explain it as such when giving the description as Thomas noted</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Ah yea I guess not, I thought they were</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>awesome! I would emphasis unpooled then (which I assume you would do anyway :D)</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Reworded that paragraph. LMK what you guys think</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Thanks. So I understand how to interpret it, but what I don't understand is what a "ranked" sample is: samples are samples, how can you rank them? Is that in increasing order?</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Yeah, added the link too ;)</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Thanks Ravin. Yeah, I was planning to explain how you come to that conclusion in the video. You think it'd be useful to have that here too @Thomas?</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>That's what I thought. But I agree the link should be changed to this afterwards</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Thanks</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by canyon289** [comment]
<p>Yep exactly</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Ok thanks, I get it now</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
@canyon289 @twiecki the revised version is ready for review 🥳

**Comment by canyon289** [comment]
I'll get to it today! thank you

**Comment by canyon289** [comment]
@AlexAndorra is this reviewable as rise slides? Viewing in github/nbreview its looking awesome. Now I want to check it out "as the viewer will see it"

**Comment by AlexAndorra** [comment]
Not yet, let me do that today

**Comment by canyon289** [comment]
Thanks for updating, were definitely converging.

Removing the long sentences help, but I think there should be a *little* bit of text, notably
* Headers
* Snippets of explanatory text
* Code comments

Below are some good slides from Thomas, and one of mine. Even in mine though I need to cut down the second sentence, either breaking it up into bullets or splitting it above and below the image. Its a tricky balance!

image
image
image

**Comment by AlexAndorra** [comment]
<p>Combined it with the next code block</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Sure</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Ah yes, I'll live-code that!</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Updated according to latest comments @canyon289 and @twiecki

**Comment by canyon289** [comment]
This is getting there, heres my final round of comments
Some of these slides look like theyre going to need scroll available
image

This is what im seeing for the model graph output, if its not what youre seeing ignore this comment
image

Adding one line of markdown or a comment explaining what you're doing for slides like this would beneficial in my opinion, even if you're going to talk about whats going to happen. For example

_Lets take a log transform of all our covariates_
I say this so we can hit all [three types](https://www.missouristate.edu/Assets/busadv/p-30.pdf) of learning.

image

**Comment by canyon289** [comment]
Remember that bullet point could be removed, or if you keep it indented towards the right.
image

Would change title to MCMC Sampling Convergence Checks, so we can reinforce the word sampling which is the theme of the course

image

In Intrepreting parameters i would change the traceplot to `az.plot_posterior`. That way the focus is on the parameter interpretation, theres more visual elements to facilitate interpretation, and we can show off another tool in context.
image

**Comment by canyon289** [comment]
A number of slides are still missing headers, and a lesser amount are missing text. For instance at a glance what's the takeway of this slide?

image

**Comment by AlexAndorra** [comment]
<p>Yes, that works well on my end</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>This is the only thing I need to merge this PR and start recording. Any news on this Ravin?</p><p> </p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Now this should be all good to go @canyon289 🥳

**Comment by canyon289** [comment]
Consider this approved. Final comments

1. More title additions in all sections including and after A Simple PyMC Example, just like the ones you added would be good
2. This slide still has a lot of boilerplate code that distracts from the message

image

**Comment by canyon289** [comment]
<p>Hey, I missed this comment sorry. Did I get you what you needed? I know im holding you up so ping me on discord as much as you need since I see that much faster than I do gh comments. Sorry for any delay I caused</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Great point, added</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>But both will still be in the NB, won't they? In which case that will be weird for readers to see the same points twice -- that's why I did that</p>

---

 <a href='https://app.reviewnb.com/AlexAndorra/notebooks-experiments/pull/4/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
80 incorporates my feedback - looks great!

**Pull request closed without merging**
